#!/usr/bin/env node
// Phasera build-time SEO validator. Zero dependencies.
// Usage:
//   node scripts/seo-check.mjs           # validates index.html, /cases/*, sitemap, robots; exits 1 on failure
//
// The sitemap.xml is generated by scripts/build-cases.mjs (run first in `vercel-build`);
// this script only validates — it does not write.

import { readFileSync, existsSync, readdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

const ORIGIN = 'https://phasera.jp'
const CANONICAL = `${ORIGIN}/`
const REQUIRED_SCHEMA_TYPES = ['Organization', 'WebSite', 'Service', 'FAQPage']
const TITLE_MIN = 30, TITLE_MAX = 60
const DESC_MIN = 70, DESC_MAX = 160

const fails = []
const warns = []
const fail = (file, msg) => fails.push(`[FAIL] ${file}: ${msg}`)
const warn = (file, msg) => warns.push(`[WARN] ${file}: ${msg}`)
const pass = []

// Collect every @type present in a parsed JSON-LD object graph.
const collectTypes = (node, set) => {
  if (!node || typeof node !== 'object') return set
  if (Array.isArray(node)) { node.forEach((n) => collectTypes(n, set)); return set }
  if (node['@type']) {
    const t = node['@type']
    if (Array.isArray(t)) t.forEach((x) => set.add(x))
    else set.add(t)
  }
  for (const k of Object.keys(node)) collectTypes(node[k], set)
  return set
}

const html = readFileSync(join(ROOT, 'index.html'), 'utf8')
const sitemap = readFileSync(join(ROOT, 'sitemap.xml'), 'utf8')
const robots = readFileSync(join(ROOT, 'robots.txt'), 'utf8')

// --- index.html checks ---

// 1. <html lang="ja">
if (!/<html[^>]+lang=["']ja["']/i.test(html)) fail('index.html', '<html lang="ja"> not found')
else pass.push('html lang')

// 2. title length
const titleMatch = html.match(/<title>([^<]+)<\/title>/)
if (!titleMatch) fail('index.html', '<title> not found')
else {
  const t = titleMatch[1].trim()
  const len = Array.from(t).length
  if (len < TITLE_MIN || len > TITLE_MAX) fail('index.html', `title length ${len} not in [${TITLE_MIN},${TITLE_MAX}] — "${t}"`)
  else pass.push(`title length ${len}`)
}

// 3. meta description length
const descMatch = html.match(/<meta\s+name=["']description["']\s+content=["']([^"']+)["']/i)
if (!descMatch) fail('index.html', 'meta description not found')
else {
  const d = descMatch[1].trim()
  const len = Array.from(d).length
  if (len < DESC_MIN || len > DESC_MAX) fail('index.html', `description length ${len} not in [${DESC_MIN},${DESC_MAX}]`)
  else pass.push(`description length ${len}`)
}

// 4. canonical
const canonMatch = html.match(/<link\s+rel=["']canonical["']\s+href=["']([^"']+)["']/i)
if (!canonMatch) fail('index.html', 'canonical link not found')
else if (canonMatch[1] !== CANONICAL) fail('index.html', `canonical "${canonMatch[1]}" !== "${CANONICAL}"`)
else pass.push('canonical')

// 5. robots meta
if (!/<meta\s+name=["']robots["']/i.test(html)) warn('index.html', 'explicit <meta name="robots"> missing (defaults to index,follow)')
else pass.push('robots meta')

// 5b. deploy-safety: production HTML must NEVER ship noindex (regression guard against the
//     "bad deploy deindexed us" incident). Scans every robots meta tag for a noindex token.
const robotsTags = [...html.matchAll(/<meta\b[^>]*\bname=["']robots["'][^>]*>/gi)].map((m) => m[0])
const noindexTags = robotsTags.filter((tag) => /\bnoindex\b/i.test(tag))
if (noindexTags.length > 0) fail('index.html', `production robots meta must not contain noindex: ${noindexTags.join(' ; ')}`)
else pass.push('no noindex in production HTML')

// 6. h1 exactly 1
const h1Count = (html.match(/<h1[\s>]/gi) || []).length
if (h1Count !== 1) fail('index.html', `expected exactly 1 <h1>, found ${h1Count}`)
else pass.push('single h1')

// 7. all <img> have non-empty alt
const imgs = [...html.matchAll(/<img\s+([^>]*)>/gi)]
let imgFails = 0
for (const [, attrs] of imgs) {
  const altMatch = attrs.match(/\balt=["']([^"']*)["']/i)
  if (!altMatch || altMatch[1].trim() === '') imgFails++
}
if (imgFails > 0) fail('index.html', `${imgFails} <img> with missing/empty alt`)
else pass.push(`img alt (${imgs.length} images)`)

// 8. JSON-LD parses + required @types present
const jsonLds = [...html.matchAll(/<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)]
if (jsonLds.length === 0) fail('index.html', 'no JSON-LD <script> blocks')
const seenTypes = new Set()
for (let i = 0; i < jsonLds.length; i++) {
  try {
    collectTypes(JSON.parse(jsonLds[i][1].trim()), seenTypes)
  } catch (e) {
    fail('index.html', `JSON-LD block #${i + 1} parse error: ${e.message}`)
  }
}
for (const t of REQUIRED_SCHEMA_TYPES) {
  if (!seenTypes.has(t)) fail('index.html', `JSON-LD missing required @type "${t}"`)
}
if (jsonLds.length > 0) pass.push(`JSON-LD parsed (types: ${[...seenTypes].join(', ')})`)

// 9. all internal href="#id" point to existing section IDs
const sectionIds = new Set([...html.matchAll(/<section[^>]+id=["']([^"']+)["']/gi)].map((m) => m[1]))
const idHrefs = [...html.matchAll(/href=["']#([^"'\s]+)["']/gi)].map((m) => m[1]).filter((id) => id && id !== '')
const missingAnchors = [...new Set(idHrefs.filter((id) => !sectionIds.has(id)))]
if (missingAnchors.length > 0) fail('index.html', `href anchors missing section: ${missingAnchors.join(', ')}`)
else pass.push(`anchors (${sectionIds.size} sections, ${idHrefs.length} links)`)

// --- sitemap.xml checks ---

// 10. all <loc> start with CANONICAL and contain no fragments
const locs = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1].trim())
if (locs.length === 0) fail('sitemap.xml', 'no <loc> entries')
let badLocs = 0
for (const loc of locs) {
  if (!loc.startsWith(CANONICAL)) { fail('sitemap.xml', `loc must start with ${CANONICAL}: "${loc}"`); badLocs++ }
  if (loc.includes('#')) { fail('sitemap.xml', `loc must not contain fragment: "${loc}"`); badLocs++ }
}
if (badLocs === 0) pass.push(`sitemap locs (${locs.length})`)

// --- robots.txt checks ---

// 11. Sitemap: line present
if (!/^Sitemap:\s*https?:\/\//mi.test(robots)) fail('robots.txt', 'no Sitemap: line')
else pass.push('robots Sitemap line')

// --- /cases/* checks (generated by scripts/build-cases.mjs) ---
// These are the consolidated case-study pages that replaced the separate
// phasera-blog.vercel.app domain. They must live on phasera.jp with correct
// canonicals so the SEO value accrues to the main site.
const CASES_DIR = join(ROOT, 'cases')
if (!existsSync(CASES_DIR)) {
  fail('cases/', 'directory missing — run `node scripts/build-cases.mjs` (wired into vercel-build)')
} else {
  const validateCasePage = (label, file, expectedCanonical, requiredTypes) => {
    const doc = readFileSync(file, 'utf8')
    if (!/<html[^>]+lang=["']ja["']/i.test(doc)) fail(label, '<html lang="ja"> not found')
    // exactly one h1
    const h1 = (doc.match(/<h1[\s>]/gi) || []).length
    if (h1 !== 1) fail(label, `expected exactly 1 <h1>, found ${h1}`)
    // canonical
    const c = doc.match(/<link\s+rel=["']canonical["']\s+href=["']([^"']+)["']/i)
    if (!c) fail(label, 'canonical link not found')
    else if (c[1] !== expectedCanonical) fail(label, `canonical "${c[1]}" !== "${expectedCanonical}"`)
    // non-empty meta description
    const d = doc.match(/<meta\s+name=["']description["']\s+content=["']([^"']*)["']/i)
    if (!d || d[1].trim() === '') fail(label, 'meta description missing/empty')
    // must NOT ship noindex (same deploy-safety guard as the homepage)
    const rtags = [...doc.matchAll(/<meta\b[^>]*\bname=["']robots["'][^>]*>/gi)].map((m) => m[0])
    if (rtags.some((t) => /\bnoindex\b/i.test(t))) fail(label, 'robots meta must not contain noindex')
    // JSON-LD parses and carries the required @types
    const blocks = [...doc.matchAll(/<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)]
    const types = new Set()
    if (blocks.length === 0) fail(label, 'no JSON-LD block')
    for (let i = 0; i < blocks.length; i++) {
      try { collectTypes(JSON.parse(blocks[i][1].trim()), types) }
      catch (e) { fail(label, `JSON-LD parse error: ${e.message}`) }
    }
    for (const t of requiredTypes) if (!types.has(t)) fail(label, `JSON-LD missing @type "${t}"`)
    return { canonical: expectedCanonical }
  }

  const caseCanonicals = []

  // hub
  const hubFile = join(CASES_DIR, 'index.html')
  if (!existsSync(hubFile)) fail('cases/index.html', 'hub page missing')
  else {
    validateCasePage('cases/index.html', hubFile, `${ORIGIN}/cases/`, ['CollectionPage', 'BreadcrumbList', 'ItemList'])
    caseCanonicals.push(`${ORIGIN}/cases/`)
  }

  // each article
  const slugs = readdirSync(CASES_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort()
  if (slugs.length === 0) fail('cases/', 'no article subdirectories found')
  for (const slug of slugs) {
    const f = join(CASES_DIR, slug, 'index.html')
    if (!existsSync(f)) { fail(`cases/${slug}/`, 'index.html missing'); continue }
    const canonical = `${ORIGIN}/cases/${slug}/`
    validateCasePage(`cases/${slug}/index.html`, f, canonical, ['Article', 'BreadcrumbList'])
    caseCanonicals.push(canonical)
  }
  if (fails.every((f) => !f.includes('cases/'))) pass.push(`cases pages (${slugs.length} articles + hub)`)

  // 12. sitemap must cover every case page (and the homepage)
  const locSet = new Set(locs)
  const missingInSitemap = [CANONICAL, ...caseCanonicals].filter((u) => !locSet.has(u))
  if (missingInSitemap.length > 0) fail('sitemap.xml', `missing URLs: ${missingInSitemap.join(', ')}`)
  else pass.push(`sitemap covers homepage + ${caseCanonicals.length} cases URLs`)
}

// --- report ---
const stamp = new Date().toISOString()
console.log(`# Phasera SEO check (${stamp})`)
for (const p of pass) console.log(`[PASS] ${p}`)
for (const w of warns) console.log(w)
for (const f of fails) console.log(f)
console.log(`# ${pass.length} pass · ${warns.length} warn · ${fails.length} fail`)

process.exit(fails.length > 0 ? 1 : 0)
